### ISSUE TITLE
Trial deploying machine learning model to device

### ISSUE THREAD

**Issue by livgrhm** [Welthungerhilfe/cgm-scanner#96]

**Comment by livgrhm** [comment]
## Approach
1. Obtain frozen version of TensorFlow model as a protobuf file
    - Option 1 [done]: convert .h5 keras file to .pb file (script available, needs reviewing)
    - Option 2: spit out .pb files straight after the training process, rather than spitting out as .h5 file
2. Save this protobuf file to the app's asset directory
3. Build all necessary .so and .jar tensorflow inference libraries for different phone architectures (possibly we only need to do this for architectures used by our 2 devices); script to do all this available online (https://github.com/joytunes/tensorflow/blob/joytunes_mobile_deployment/prepare_android_deployment.sh)
4. Look into slimming down the size of these libs (https://medium.com/joytunes/slimming-down-tensorflows-impact-on-your-apk-size-9b5cb07e6238)
5. Copy lib directory into project & add to gradle file to load the tensorflow inference libraries
6. Code in app to load the model, input scan data, retrieve and display the height/weight result.
7. Deploy new version to the play store. Updates to the model can be deployed in this way.

##  Open Questions (and some answers)
1. Is it absolutely necessary for the frozen model to be protobuf?
2. Why .h5 vs .pb - what's the difference/pros/cons
3. TensorFlow Lite or TensorFlow Mobile? (TensorFlow Lite seems better but still in development mode - ask Nora about MM)
4. Automatically deploying new/changed models - is the best way deploying new app versions with the newer model?
5. Size of the packaged models - what becomes a problem for the app? Nora said max 1MB, .pb file generated from .h5 file during tests is 3.7MB. Understanding of where the limits are, how might this model grow
    - *issue 1*; tensorflow inference libraries increasing size of .APK
        - raw file sizes of libs **52MB** -> additional 16MB download size
        - BUT if you apply 'selective registration' to the libs (remove everything that is not needed for the specific model) then raw file size **36MB**.
    - *issue 2*: size of actual .pb model file (current = 3.7MB)
        - Google Play currently requires that your APK file be no more than 100MB

**Comment by xMartin** [comment]
Google's ML Kit could be considered as an alternative:

> [...] you can always bring your own existing TensorFlow Lite models. Just upload your model to Firebase, and we'll take care of hosting and serving it to your app. ML Kit acts as an API layer to your custom model, making it simpler to run and use.

https://firebase.google.com/docs/ml-kit/

I assume for our use-case it

 * syncs the model to the phone so it's somehow offline-capable (because Firebase is partly about syncing)
 * provides a high-level Android API to use the model to get prediction on top of Tensorflow lite

Open questions:

 * How reliable is it in the offline case?
 * How much value does it provide for us compared to figuring out our own way how to get the model on the phone and using the Tensorflow lite API directly?

Note: ML Kit mainly offers integrated pre-built models for common ML tasks which is not relevant to us.
